### ISSUE TITLE
RegEx ASCII Special Characters

### ISSUE THREAD

**Issue by albertopfunk** [lorey/social-media-profiles-regexs#19]
As I was testing some patterns, I noticed that you used 'A-z' for alphanumeric characters. When you do that, it will match any character between 65-122 ASCII, that includes lowercase, uppercase, and a few special characters, including underscores. To fix that and only include characters a-z(97-122) and A-Z(65-90), you need to change 'A-z' to 'a-zA-Z'

**Comment by lorey** [comment]
Hey Alberto, thanks for reaching out. 

This is mostly done on purpose because of laziness. These regular expressions are for crawling/scraping, not for validation. And for scraping a higher [recall is more important than precision](https://en.wikipedia.org/wiki/Precision_and_recall) IMHO.

What do you think?

**Comment by albertopfunk** [comment]
gotcha that makes sense, I was using them for validation, apologies for that misunderstanding. I ended up your examples as a starting point for some I created, very helpful, thank you!
